void testAnimals(void);
struct Animal* createDog(char const* name);
struct Animal* createCat(char const* name);
void constructDog(struct Animal* dog, char const* name);
void constructCat(struct Animal* cat, char const* name);
char const* dogGreet(void);
char const* catGreet(void);
char const* dogMenu(void);
char const* catMenu(void);
void animalPrintGreeting(struct Animal* animal);
void animalPrintMenu(struct Animal* animal);